name: Depicting usage of Docker Container image.

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Lode node version
        run: |
          node -v
          cat /etc/os-release