# Configuring 3 environments with protection rules n secrets.
# DEC environment has no protection rule but 1 secret value.
# QA environment has a protection rule of 'Wait timer' of 1 minute.
# PROD environment has a protection rule of 1 'Required reviewers' approval. 
name: Configuring 3 environments with protection rules and secrets.

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  job-DEV:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running a job in the DEV environment"
          
          
  job-QA:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running a job in the QA environment"
          
  job-PROD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running a job in the PROD environment"