# GitHub workflow hides and encrypts the secret value. It does not diplay secret value, rather it displys ***

name: Secrets example
on: push
jobs:
  job-secret-example:
    runs-on: ubuntu-latest
    steps:
      - name: Testing secret value is correct/incorrect
        run: |
          if [ "$CANDY_SECURE" == "candy" ]
          then
            echo "Got secret   candy=${{ secrets.CANY_APPLE_SECURE }}"
          fi
        env: 
          CANDY_SECURE: ${{ secrets.CANY_APPLE_SECURE }}

      
      # Showing how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable with if condition 
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if:  env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know what the secret token is!"

      # A GitHub Actions if statement with a secret environment variable in a bash shell
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if:  env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
