# GitHub workflow hides and encrypts the secret value. It does not diplay secret value, rather it displys ***

name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Testing secret value is correct/incorrect
        run: |
          if [ "$CANDY_SECURE" == "candy" ]
          then
            echo "Got secret   candy=${{ secrets.CANY_APPLE_SECURE }}"
          fi
        env: 
          CANDY_SECURE: ${{ secrets.CANY_APPLE_SECURE }}
