// GitHub workflow hides and encrypts the secret value. It does not diplay secret value, rather it displys ***.

name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "The value of secret is   ${{ secrets.SAMPLE_PASSWORD }} !"
        echo $SAMPLE_PASSWORD
      - name: Test
        run: |
          if [ "$CANDY_SECURE" == "candy" ]
          then
            echo "Got secret"
          fi
        env: 
          CANDY_SECURE: ${{ secrets.CANY_APPLE_SECURE }}
