# sending a slack message from GitHub personal repository to a channel of Slack using Docker image technosophos/slack-notify
# Example: general channel of app.slack.com. Follow below steps:
# Go to api.slack.com  > Create a Custom App > Create an App from scratch > Once app is created > 
# > Got to Incoming webhooks > Turn ON "Activate Incoming Webhooks" > Add new webhook to workspace
# > select channel like general and Allow > copy webhook URL and paste in SLACK_WEBHOOK secret token. 

name: sending a slack message from GitHub   
on: push

jobs:
  job-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Sending Hello World message from GitHub personal repository"
  